version: '3.9'
services:
  database:
    image: postgres:11.2
    ports:
      - "5432:5432"
    volumes:
      - ./pgData:/var/lib/psotgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: codemonday
  app:
    working_dir: /app
    entrypoint: ["/bin/bash", "./entrypoint.sh"]
    image: node:12
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - database
    environment:
      SERVER_PORT: '3000'
      DATABASE_CONNECTION: 'postgres://postgres@database/codemonday'
